import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
// import localFont from "next/font/local";
// @ts-ignore
import "./globals.css";
import PublicNavbar from "./(public)/_components/publicNavbar/PublicNavbar";
import FooterSection from "@/shared/components/home/FooterSection";
import { RouteProvider } from "@/shared/providers/route/RouteProvider";
import NavbarWithRouteRules from "./(public)/_components/publicNavbar/NavbarWithRouteRules";
import { TwScreenSize } from "@/shared/components/TwScreenSize";
import LenisProvider from "@/shared/providers/LenisProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Model Boss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="custom-scroll">
      <body
        className={`${inter.variable} ${manrope.variable} antialiased `}
      >

        <RouteProvider>
          <LenisProvider>
            {children}
          </LenisProvider>
        </RouteProvider>
        <TwScreenSize/>
      </body>
    </html>
  );
}
