import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { RouteProvider } from "@/shared/providers/route/RouteProvider";

import LenisProvider from "@/shared/providers/LenisProvider";
import StoreProvider from "@/redux/StoreProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Model Boss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="custom-scroll">
      <body
        className={`${inter.variable} ${manrope.variable} antialiased `}
      > 
        <StoreProvider>
        <LenisProvider>
          <RouteProvider>
            {children}
          </RouteProvider>
          </LenisProvider>
        </StoreProvider>
        {/* <TwScreenSize/> */}
      </body>
    </html>
  );
}
