import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
// import localFont from "next/font/local";
// @ts-ignore
import "./globals.css";
import PublicNavbar from "./(public)/_components/publicNavbar/PublicNavbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-manrope",
  display: "swap",
});
// const avenir = localFont({
//   src: [{ path: "../../public/fonts/Avenir-Heavy.woff2", weight: "800", style: "normal" }],
//   variable: "--font-avenir",
//   display: "swap",
// });
export const metadata: Metadata = {
  title: "Model Boss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="custom-scroll">
      <body
        className={`${inter.variable} ${manrope.variable} antialiased `}
      >
        <PublicNavbar />
        {children}
      </body>
    </html>
  );
}
